module.exports = {
  logo: require('./images/logo.png'),
  home: require('./images/home.png'),
  profile: require('./images/profile.png'),
  more: require('./images/more.png'),
  close: require('./images/close.png'),
  eye: require('./images/eye.png'),
  eye_off: require('./images/eye_off.png'),
  antMan: require('./images/antMan.jpeg'),
  captain: require('./images/captain.jpeg'),
  hulk: require('./images/hulk.jpg'),
  ironMan: require('./images/ironMan.jpeg'),
  panther: require('./images/panther.jpeg'),
  spider: require('./images/spider.jpeg'),
  thor: require('./images/thor.jpg'),
  strange: require('./images/strange.jpeg'),
  login: require('./images/login.png'),
  language: require('./images/language.png'),
  theme: require('./images/theme.png'),
  avatar: require('./images/avatar.png'),
  editing: require('./images/editing.png'),
  phone: require('./images/phone.png'),
  email: require('./images/email.png'),
  idCard: require('./images/idCard.png'),
  MLogo: require('./images/M.png'),
  notAvailable: require('./images/notAvailable.png'),
  reload: require('./images/reload.png'),
};
